FIELD_LABELS = {
    "id": "ID",
    "mes_id_name": "Name message key",
    "mes_id_description": "Description message key",
    "lv": "Level",
    "hp": "HP",
    "mp": "MP",
    "hp_value1": "Strong HP growth flags",
    "mp_value1": "MP growth",
    "strength": "Strength",
    "vitality": "Vitality",
    "agility": "Agility / Dexterity",
    "intelligence": "Intelligence",
    "spirit": "Spirit / Wisdom",
    "magic": "Magic",
    "luck": "Luck",
    "attack": "Attack",
    "defense": "Defense",
    "attack_count": "Attack count",
    "accuracy_rate": "Accuracy",
    "evasion_rate": "Evasion",
    "magic_evasion_rate": "Magic evasion",
    "critical_rate": "Critical rate",
    "exp": "EXP reward",
    "gill": "Gil reward",
    "boss": "Boss flag",
    "drop_rate": "Drop rate",
    "drop_content_id1": "Drop item/content",
    "drop_content_id1_value": "Drop quantity",
    "script_id": "AI script",
    "monster_asset_id": "Monster asset",
    "initial_condition": "Initial condition",
}

def friendly_label(field: str) -> str:
    return FIELD_LABELS.get(field, field.replace("_", " ").title())
